debug: true
logger:
  prefix: ""
  stdout: "stdout"       # stdout: 输出到控制台  file: 输出到文件 其他: 同时写入文件并输出到控制台
  file: "log"
  log_level: 1           # 0：PanicLevel 1: ErrorLevel 2: WarnLevel 3: InfoLevel 4: DebugLevel
web_config:
  address: "0.0.0.0"
  port: 9999
kafka:
  topic: ["XXX"]
  group_id: "XXX"
  bootstrap_servers: "XXX:XX,XXX:XX,XXX:XX"
  security_protocol: "PLAINTEXT"
  sasl_mechanism: "PLAIN"
  sasl_username: "XXX"
  sasl_password: "XXX"
db:
  -
    driver: "mysql"
    host: "xxxx"
    port: 3306
    database: "xxx"
    username: "root"
    password: "xxx"
    charset: "utf-8"
    max_idle_conns: 100
    max_open_conns: 10
  -
    driver: "postgres"
    host: "xxxx"
    port: 3306
    database: "xxx"
    username: "root"
    password: "xxx"
    charset: "utf-8"
    max_idle_conns: 100
    max_open_conns: 10
redis:
  address: "xxx"
  port: 6379
  password: "xxx"
  index_db: 0
  max_idle_conns: 100
  max_open_conns: 100
  max_active: 10
  conn_timeout: 30
  max_retry_times: 5
  re_connect_interval: 3
es:
  host: [""]
  username: ""
  password: ""
mongo:
  host: ""
  user: ""
  password: ""
  max_pool_size: 1
  connect_timeout: 1000
  max_conn_idle_time: 10000